name: 01EventosLast

on:
  schedule:
    - cron: '1 4 * * *'   # Diario a las 04:01 UTC
  workflow_dispatch:

jobs:
  scrape-and-upload:
    runs-on: ubuntu-22.04
    env:
      TZ: Europe/Madrid
      HEADLESS: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome-stable --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager beautifulsoup4 lxml requests

      - name: Prepare output dir
        run: mkdir -p ./output

      - name: Run 01EventosLast.py
        env:
          # (Opcional) Mueve credenciales a secrets y léelas en el script
          FLOW_EMAIL: ${{ secrets.FLOW_EMAIL }}
          FLOW_PASS:  ${{ secrets.FLOW_PASS }}
        run: |
          set -e
          echo "=== Ejecutando 01EventosLast.py ==="
          python ./01EventosLast.py
          echo "=== Fin de 01EventosLast.py ==="

      - name: Verify output
        run: |
          set -e
          echo '=== Verificando archivo generado ==='
          ls -la ./output || true
          test -f ./output/01events_past.json
          BYTES=$(stat -c%s ./output/01events_past.json)
          echo "✅ 01events_past.json encontrado (${BYTES} bytes)"

      - name: Compress JSON (gzip)
        run: |
          gzip -9 -c ./output/01events_past.json > ./output/01events_past.json.gz
          ls -la ./output/01events_past.json.gz

      - name: Upload to FTP with lftp (FTPS, retries, mkdir -p)
        env:
          FTP_SERVER:     ${{ secrets.FTP_SERVER }}      # solo host, sin ftp://
          FTP_USERNAME:   ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD:   ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}  # ej: /public_html (sin / final)
        run: |
          set -euo pipefail

          sudo apt-get update && sudo apt-get install -y lftp

          _server_raw="${FTP_SERVER:-}"
          _rdir_raw="${FTP_REMOTE_DIR:-}"

          FTP_SERVER_CLEAN="$(printf '%s' "$_server_raw" | tr -d '\r\n' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's#^ftp://##')"
          FTP_REMOTE_DIR_CLEAN="$(printf '%s' "$_rdir_raw" | tr -d '\r\n' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's#/*$##')"
          if [ -n "$FTP_REMOTE_DIR_CLEAN" ] && [ "${FTP_REMOTE_DIR_CLEAN#/}" = "$FTP_REMOTE_DIR_CLEAN" ]; then
            FTP_REMOTE_DIR_CLEAN="/$FTP_REMOTE_DIR_CLEAN"
          fi

          REMOTE_DIR="${FTP_REMOTE_DIR_CLEAN}/Competiciones/EventosLast/data"

          echo "Subiendo a: ftps://${FTP_SERVER_CLEAN}${REMOTE_DIR}/"

          lftp -e "
            set ssl:verify-certificate no;
            set ftp:ssl-force true;              # FTPS explícito
            set ftp:ssl-protect-data true;       # Protege canal de datos (PROT P)
            set net:max-retries 2;
            set net:timeout 30;
            set net:persist-retries 1;
            set xfer:clobber on;                 # sobreescribir
            mkdir -p ${REMOTE_DIR};
            cd ${REMOTE_DIR};
            put -O . ./output/01events_past.json.gz;
            put -O . ./output/01events_past.json;
            bye
          " -u "${FTP_USERNAME}","${FTP_PASSWORD}" "ftps://${FTP_SERVER_CLEAN}"

      - name: Save artifacts (backup)
        uses: actions/upload-artifact@v4
        with:
          name: eventos-last-json
          path: |
            ./output/01events_past.json
            ./output/01events_past.json.gz
          retention-days: 7

      - name: Debug on failure
        if: failure()
        run: |
          echo "=== DEBUG ==="
          ls -la ./output || true
          which google-chrome-stable || true
          google-chrome-stable --version || true
